#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
  path: /
  controller: App\Controller\IndexController::init
Login:
  path: /Login
  controller: App\Controller\AuthController::login
Register:
  path: /Register
  controller: App\Controller\RegistrationController::register
